Repository githubschool/fra-14, pull requests merged in 2018-03, with the labels that each got.

#16 Xh077 adds a few newlines
  _posts/0000-01-02-schasan.md
Labels: enhancement

#22 update fabtagon's caption
  _posts/0000-01-08-fabtagon.md
Labels: aaaaaaaaaa, lol stuff

#24 beardofedu's caption
  _posts/0000-01-45-beardofedu.md
Labels: enhancement

#21 Test - file geaendert....
  _posts/0000-01-99-Florian.md
Labels: SuperDuperLabel

#25 Albechr caption (the best)
  READMEmine.md
  _posts/0000-01-07-albechr.md
Labels: famous change, supi

#29 sathariel74: Changed _posts/0000-01-04-sathariel74.md with new caption and image URL
  _posts/0000-01-04-sathariel74.md
Labels: famous change
